### ISSUE TITLE
Support `auth` for requests

### ISSUE THREAD

**Issue by sreerajkksd** [prodigyeducation/python-graphql-client#26]
**Is your feature request related to a problem? Please describe.**
Support kerberos authentication to client endpoints.

**Describe the solution you'd like**
Add `auth` as an argument similar to headers during the initialization and use that while making calls.

**Comment by masudias** [comment]
I think you can easily provide the authorization key as a header as follows. 

```
client = GraphqlClient(API_URL)
client.headers = {'Authorization': 'Bearer your-long-token'}
```

**Comment by steve148** [comment]
@sreerajkksd sorry for being slow to get to you here. Thanks for posting up an issue!

If you're roughly looking for the `auth` input argument to passed on to the `requests` library, that seems like a reasonable ask to me. I'll look into it more over the weekend, but if you have an opinion on how this should be implemented feel free to claim this issue as the assignee and create a PR.

If I understand correctly, I roughly see the `execute` function changing like the following:

```python
    def execute(self, query: str, variables: dict = None, operation_name: str = None, auth=None):
        ...
        result = requests.post(self.endpoint, json=request_body, headers=self.headers, auth=auth)
```

Does the above align with what you're picturing here?

**Comment by sreerajkksd** [comment]
@steve148 that is precisely what I'm asking here.

**Comment by DaleSeo** [comment]
Hi @sreerajkksd! I put up a PR to address this your feature request. Please let me know if it will work for you.

https://github.com/prodigyeducation/python-graphql-client/blob/8a6da932a3d6e27ab25d4f1c1a4f7c0a425b3807/tests/test_graphql_client.py#L102-L118
