### ISSUE TITLE
Turning off SSL verification for API requests

### ISSUE THREAD

**Issue by masudias** [prodigyeducation/python-graphql-client#32]
I am not sure if we have this already, however, I could not figure a way to turn off the SSL verification for the API requests using this library. 

I think we could pass an optional `**kwargs` while initializing the client so that we could pass those optional attributes while calling the APIs using `requests` library. 

The initialization could be the following. 

```client = GraphqlClient("http://www.my.api.server.com/graphql", verify=False)```

**Comment by DaleSeo** [comment]
Thank you for opening an issue, @masudias. I put up a PR to address your issue. Please let me know if it will work for you.

https://github.com/prodigyeducation/python-graphql-client/blob/3852c5526e42be9e843b948bd8a487a6ad76fff9/tests/test_graphql_client.py#L101-L116
