### ISSUE TITLE
Add support for graphql subscriptions

### ISSUE THREAD

**Issue by steve148** [prodigyeducation/python-graphql-client#4]
**Is your feature request related to a problem? Please describe.**

Right now the project supports both synchronous and asynchronous queries against a GraphQL server. One piece of the graphql specification that we don't currently support is creating a connection to a graphql server to read a subscription. If we want to move towards being graphql spec compliant, this is something we should include here.

**Describe the solution you'd like**

I don't have an exact solution in mind here. For the initial version of the feature. We can support a single transport protocol for the subscriptions like web sockets, but in the long run we should look at making it flexible so we can plug in different transport layers without having to change much in the design.

**Describe alternatives you've considered**

No alternatives to the subscriptions from the Graphql spec, but there are a set of alternatives as what the transport protocol looks like for doing the subscriptions. It should be web sockets like https://github.com/apollographql/subscriptions-transport-ws or using server side events like in this node implementation https://github.com/chrisdickinson/sse-stream.

**Additional context**

N/A

**Comment by DaleSeo** [comment]
@steve148 Do you mind me taking on this issue?

**Comment by steve148** [comment]
Not at all! Take a stab at it :hocho:
