### ISSUE TITLE
Allow users to use more recent versions of dependencies

### ISSUE THREAD

**Issue by DaleSeo** [prodigyeducation/python-graphql-client#40]
**Is your feature request related to a problem? Please describe.**

We've pinned dependencies in `setup.py`, which means users need to install the specific versions of our dependencies. If any users need to use a more recent version, we need to update it in `setup.py` or they need to create a PR like #38. This feels like an unreasonable maintenance overhead.

https://github.com/prodigyeducation/python-graphql-client/blob/6ab30cffd3096d0530745b80cd468281ec029655/setup.py#L32

**Describe the solution you'd like**

If we specify versions using a more flexible operator like `>=`, users will be able to use the latest version of our dependencies.

- https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
- https://www.python.org/dev/peps/pep-0440/#inclusive-ordered-comparison

**Describe alternatives you've considered**

**Additional context**

**Comment by steve148** [comment]
Thanks for creating this ticket! If it's ok with you, I got some time today and can take a stab at this one. I already have an idea of what versions they can be pinned at for the `>=` clause.

**Comment by DaleSeo** [comment]
@steve148 Please go ahead!
