### ISSUE TITLE
Disable client logs

### ISSUE THREAD

**Issue by nadavtsa** [prodigyeducation/python-graphql-client#43]
Hi, is there a way to disable the logging produced by the client? 

If not, I think it's a good idea to add these feature.

Thank you :)

**Comment by DaleSeo** [comment]
Hi @nadavtsa, thank you for the issue. The following code is setting the logging level to `INFO` and I'm looking to make it configurable. Please feel let me know if you have any ideas on how to go about this.

https://github.com/prodigyeducation/python-graphql-client/blob/1e6df927963c12cb09f4843662177ca9a509e408/python_graphql_client/graphql_client.py#L10
