### ISSUE TITLE
Automate changelog generation

### ISSUE THREAD

**Issue by steve148** [prodigyeducation/python-graphql-client#5]
**Is your feature request related to a problem? Please describe.**

Right now we don't have a changelog for how the project is changing over time. This means that there's no clear depiction of what has changed between versions of a project.

**Describe the solution you'd like**

There needs to be a changelog which in its most minimal version will list the version number, date / time when the release was created, and a list of changes included in the release.

Ideally this changelog would be automatically generated whenever we release to PyPi with no manual work required by maintainers or contributors.

**Describe alternatives you've considered**

We could manualy create a changelog on each. Downside is that it requires work. We may need to manually edit the changelog anyway to make sure the release notes are digestable.

**Additional context**

**Comment by ChrisZhangProdigy** [comment]
@steve148 can I take this one?

**Comment by steve148** [comment]
I think this can be closed for now, as @ChrisZhangProdigy has done the work to provide at least some utility methods for creating the changelog. Thanks for that @ChrisZhangProdigy :pray:
